### ISSUE TITLE
Determine success or failure of an NIH deposit from emailed status updates

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/deposit-services#125]
The NIHMS system will send an email for each package dropped off at their FTP server, indicating whether or not the package has been accepted.

This issue presents the notion of retrieving this email in a programmatic fashion, parsing the email, and updating the status of the `Deposit` based on the email's contents.

Some considerations:

If the NIH rejects a package, do we mark the `Deposit` as `REJECTED` (a _terminal_ state)?  The user would be forced to create a new submission in the UI in order to retry the deposit to NIH.  This might be appropriate if the user provided files in the submission that are unsupported by NIHMS.

Or, do we mark the `Deposit` as `FAILED` (an _intermediate_ state), manually repair the package, and manually re-upload the package to the NIH FTP server for a second try?  This might be appropriate if the issue stems from incomplete metadata required by the NIHMS packaging (cough) spec.

If the NIH accepts the package, is that enough to consider the transfer of custody complete?  If so, then the `Deposit` would be marked as `ACCEPTED`(a _terminal_ state).

**Comment by htpvu** [comment]
1 example of an error message: 

Error |   | <CustomMessage id="bulksub_xml_dtd_validation_failed"><param id="DETAIL">Error (3, 4): The element 'journal-meta' has incomplete content. List of possible elements expected: 'journal-id issn'.</param></CustomMessage>Job TaskId=nihms-native-2017-07_2018-06-24_19-06-21_196c1712-3fe4-4270-9832-59aae12a8513 was not submitted.
-- | -- | --

**Comment by emetsger** [comment]
@hvu can you paste the full source of the email, including headers?

**Comment by htpvu** [comment]
[SuccessMessageNIHMSEmailSource.txt](https://github.com/OA-PASS/nihms-submission/files/2135524/SuccessMessageNIHMSEmailSource.txt)
Success email source

**Comment by htpvu** [comment]
[NIHMS-failure1.txt](https://github.com/OA-PASS/nihms-submission/files/2177365/NIHMS-failure1.txt)

**Comment by htpvu** [comment]
[NIHMS-failure2-dtd-validation-missing-fields.txt](https://github.com/OA-PASS/nihms-submission/files/2177368/NIHMS-failure2-dtd-validation-missing-fields.txt)

**Comment by htpvu** [comment]
[NIHMS-failure3-dtd-validation-missing-fields.txt](https://github.com/OA-PASS/nihms-submission/files/2177376/NIHMS-failure3-dtd-validation-missing-fields.txt)
[NIHMS-failure4-files-not-under-rootdir.txt](https://github.com/OA-PASS/nihms-submission/files/2177380/NIHMS-failure4-files-not-under-rootdir.txt)

**Comment by htpvu** [comment]
[NIHMS-failure5-missing-puptype.txt](https://github.com/OA-PASS/nihms-submission/files/2177409/NIHMS-failure5-missing-puptype.txt)
[NIHMS-failture6-file-format-not-accepted.txt](https://github.com/OA-PASS/nihms-submission/files/2177417/NIHMS-failture6-file-format-not-accepted.txt)

**Comment by htpvu** [comment]
The outcomes of this card should include:
- more specific requirements of what information can be parsed out of emails and how they can be used
- a list of tasks it'd take to implement this feature.

**Comment by htpvu** [comment]
Draft cards to implement this feature is here https://docs.google.com/document/d/1PGdNecCNmRhMVwVpGAfhJnjCYNEwBPOv-UP-cgCrbEg/edit. This Feature will be close once its implementaiton is completed.

**Comment by jrmartino** [comment]
this has been implemented for the emails having the formats we know about so far. we may need to contact NiHMS to get a complete set of response templates in order to verify that we are handling all cases.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue has been linked to issue 825 in main.  This is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
