### ISSUE TITLE
Update Deposit Services to support proxy user model changes

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/deposit-services#150]
Apply changes to support version 3.0 of the data model. Specifically:
* Point the `pom.xml` to `java-fedora-client` version `0.4.0-SNAPSHOT`
* Update Submission model field name (`Submission.user`->`Submission.submitter`)
* Remove `aggregatedDepositStatus` and associated logic (or refactor for `submissionStatus`?)
* Update logic to calculate `submissionStatus` as appropriate (implementation depends on outcome of https://github.com/OA-PASS/general-issues/issues/18)
* Point integration tests to `oapass/indexer:0.0.14-3.0-SNAPSHOT` and `oapass/fcrepo:4.7.5-3.0-SNAPSHOT`
* Other changes as needed

**Comment by htpvu** [comment]
2 days LE

**Comment by karenhanson** [comment]
This was split into 2 PRs, the 1st PR closed this, reopening to wait for 2nd PR #160
