### ISSUE TITLE
Cut release for Deposit Service  v0.0.10

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/deposit-services#164]
This release should include additional logging of env vars, support for model v3.1

**Comment by emetsger** [comment]
Is this still needed with the 0.1.0 release complete?  Everything that was scheduled for 0.0.10 is in 0.1.0.

**Comment by emetsger** [comment]
(i.e. I propose closing this)

**Comment by htpvu** [comment]
This was done with the release of v 0.1.0
