### ISSUE TITLE
Some of the new metadata does not make it into the DSpace metadata

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/deposit-services#165]
This relates to this previous enhancement: #147
There are three issues with the metadata that ends up in DSpace:
* `dc.publisher` is missing
* The "Publication date" is missing from the citation concatenation 
* The `dc.contributer` that represents the logged in User seems to depend on `firstName`, `lastName`, which means if you only have a `displayName` an empty `dc.contributor` appears. `displayName` should be used as an alternative and in general empty names should not make it into DSpace. (the metadata of one of my DOIs is actually messed up and it may actually put a blank value in - so it does happen) 

Replicating the last one requires creating a submission when you have `displayName` but no `firstName`/`lastName`, but to replicate the first 2:
1. Enter a title and journal but no DOI, next
2. Make sure JScholarship is selected, and next through to metadata form. 
3. Enter a Publisher date (I tried both "12/12/2018" and Oct. 2018), and a Publisher. 
4. Next through to end and submit.
5. Review details, see there is a publication date and a publisher.
6. View completed deposit on DSpace - note there is no date in the citation and no `dc.publisher`.

![image](https://user-images.githubusercontent.com/4070836/47114531-15bd7f80-d22a-11e8-8f03-014ad4ddea9a.png)

![image](https://user-images.githubusercontent.com/4070836/47114605-4d2c2c00-d22a-11e8-9b14-f1af1d5580b1.png)

Version tested: Deposit services `0.9.0`, Ember `rev. d602e74a`

**Comment by karenhanson** [comment]
Adding a note here - this should be submitted to the maintenance branch of deposit-services, since master branch is now model version 3.0:
https://github.com/oa-pass/deposit-services/tree/0.0.x-maintenance

**Comment by Trumbore** [comment]
I have looked into these issues and have a couple of questions about them.

I see where the code did not accommodate submitters and pis/copis whose names were only specified using a single "display name" (authors _are_ being handled correctly).  I made the necessary change, but don't know where these contributors appear in the DSpace metadata.  We explicitly ignore the submitter when creating a list of contributors.  Can you enlighten me?

The code looks like it should include publisher names and publication dates if they are specified in the "crossref" section of the metadata (as opposed to the "common", "pmc" or "JScholarship" sections).  Is that where these values are defined in your data?  Do you have a copy of the metadata from Ember that I could test?

Our current deposit service tests cover two halves of this problem (migrating Ember metadata to the deposit service data model, then from the deposit service data model to DSpace XML), but getting this right really requires a test that spans both of those conversions and uses actual, complete data.  I am afraid I am not set up to run the Ember app, so I thought I'd start by seeing if your problematic data is handy.

**Comment by Trumbore** [comment]
After a conversation with Hanh and Karen, a couple of unknowns have been clarified.  The missing submitter Karen saw was entered as a PI, not a Submitter, and that is how it was being included in the output.  Hanh explained how the publisher name and publication date could come in the crossref section or in the common section, so the code will look in both places, with the crossref source taking precedence.  Hanh also provided some test metadata that I will use to build an end-to-end test of the functionality related to this issue.

**Comment by htpvu** [comment]
resolved as result of merging of #170
