### ISSUE TITLE
Implement necessary changes to support the wiring of arbitrary Assemblers and PackageProviders 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/deposit-services#188]
3 days LE

**Comment by emetsger** [comment]
This is done in local code, but has not been pushed to GitHub as a PR.

**Comment by emetsger** [comment]
Related PR: https://github.com/OA-PASS/deposit-services/pull/197

**Comment by htpvu** [comment]
implement is completed - PR pending completion of test suite #189
