### ISSUE TITLE
Implement updates to DS Docker image to support inclusion of arbitrary PackageProvider implementations

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/deposit-services#191]
(deployers of PASS will need to deploy a DS image that includes their PackageProvider implementations)

2 days LE

**Comment by emetsger** [comment]
Done in local code, has not yet been pushed to GitHub as a PR.

**Comment by htpvu** [comment]
implement is completed - testing and remediation will be done in later tickets (test suite #189)
