### ISSUE TITLE
Documentation for PackageProvider developers (2 days)

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/deposit-services#195]
2 days LE

**Comment by emetsger** [comment]
Initial drafts here: [Deposit Services Overview](https://docs.google.com/document/d/1hKfxDRXpSQxwSEhG3mN-ozdDfyuhCCPvniz8rP6aa7E/edit#) and [Assembler Development](https://docs.google.com/document/d/1r3EVuxjvGBfu7xxVmYPEBtoWMcpoRK69r1L5W0gX0_s/edit)
