### ISSUE TITLE
Update ModelBuilder to be compatible with changes introduced by the schema service

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/deposit-services#214]
## Required changes 
`ModelBuilder` reads the `Submission.metadata` (i.e. metadata blob) and parses it when creating a `DepositSubmission`.  The changes introduced by the schema service to the metadata blob will require updating the `ModelBuilder` to read and interpret the new blob format.

Because the _information_ contained in the blob is staying the same, there shouldn't be any need to adjust the internal model (e.g. `DepositSubmission` or `DepositMetadata`) used by Deposit Services: fields shouldn't need to be added, removed, or moved.

### Backwards compatibility with existing Submission resources
Do we want Deposit Services to be backwards-compatible with metadata blobs present in the PASS repository today?

Making this decision depends if we expect Deposit Services to process any Submissions that have the old metadata blob format in the repository:

* a Submission (with the old blob format) that has not yet been submitted but will be in the future
    * OR
* a Submission (with the old blob format) that _has_ been submitted, but has an intermediate deposit status

If *yes*, then that work must be implemented by any code for this issue, and must be illustrated in unit tests and integration tests.  The schema version or identity can be used to decide how to parse the blob.

#### Impact on other issues
Issue #215 documents the changes required to sample `Submission` graphs in the `shared-resources` module.  While #215 asks for all sample submission graphs to be updated to the latest metadata blob version, this issue will require at least one sample submission graph be added that uses the old metadada blob format.

### Backwards compatibility with future Submission resources
If we anticipate the format or information contained in the blob to change in the future, then I would suggest that the parsing logic be selected based on the schema identity or version. That way backward compatibility can be maintained as the format of the blob evolves.

**Comment by emetsger** [comment]
I don't believe that the information contained within the blob is changing, just its format.  So there shouldn't be any need to adjust the internal model used by Deposit Services: fields shouldn't need to be added, removed, or moved.

**Comment by emetsger** [comment]
If we anticipate the format or information contained in the blob to change in the future, then I would suggest that the parsing logic be selected based on the schema identity or version.  That way backward compatibility can be maintained as the format of the blob evolves.

**Comment by emetsger** [comment]
This [doc](https://docs.google.com/document/d/1rq2-NqQi73swGt38LhNjXFFcglKPx7CCq_i2LGVIXe0/edit) provides some more information about the metadata blob and its relationship to the internal Deposit Services model.

**Comment by htpvu** [comment]
@emetsger we'll by pass the optional change in 2 ways:
- for existing and deposited submissions, we'll migrate their metadata blob to the new format
- for en-route submissions that is not yet fully processed by deposit service, we'll make sure they are process before starting to roll out the new feature and migration. 

with that said is there enough information to estimate this ticket and its associated ticket #215 ?

**Comment by emetsger** [comment]
0.5 LE (a total of 1.0 LE for #214 and #215)
